name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate libs for multiple macOS support.
        run: |
          pip install delocate
      - name: add dynamic lib locations
        run: | 
          
          echo $JAVA_HOME_8_X64
          ls $JAVA_HOME_8_X64
          ls -l ${JAVA_HOME_8_X64jre}lib/server/libjvm.dylib


      - name: delocate with all listing
        run: |
          delocate-listdeps --all dist/*.whl
      # delocate-wheel -w fixed_wheels -v dist/*.whl
      # - name: isntall tox
      #   run: |
      #     pip install tox

      # - name: run tests with tox
      #   run: |
      #     tox
