name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate libs for multiple macOS support.
        run: |
          pip install delocate
      - name: add dynamic lib locations
        run: | 
          echo "print the current dir thing------------>"
          pwd
          echo "list waht's in the currrent dir............"
          ls
          echo "this would be printing ID of the lib.----------->"
          otool -D saxonpy/saxonc_home/rt/lib/libnet.dylib

      # - name: delocate with all listing
      #   run: |
      #     delocate-listdeps --all dist/*.whl
      # delocate-wheel -w fixed_wheels -v dist/*.whl
      # - name: isntall tox
      # delocate-listdeps --all dist/*.whl

      #   run: |
      #     pip install tox

      # - name: run tests with tox
      #   run: |
      #     tox
