name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [ '3.6', '3.7', '3.8', '3.9', '3.10' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: add rpath to libzip.dylib because there's none
        run: |
          echo "Note: manually added libjvm.dylib to darwin source code."
          install_name_tool -add_rpath @loader_path/. libs/darwin/rt/lib/libzip.dylib
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate wheel for multiple macOS support.
        run: |
          pip install delocate
          delocate-wheel -w fixed_wheels -v dist/*.whl
          echo "listing the fixed wheels....."
          ls fixed_wheels
      - name: install pytest, saxonpy, and test
        run: |
          pip install pytest
          pip install fixed_wheels/*.whl
          pytest test_saxonc.py
      - name: upload wheel
        env:
          TWINE_USER: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASS: ${{ secrets.TWINE_PASSWORD }}
        run: |
          pip install twine
          twine upload --verbose -u "$TWINE_USER" -p "$TWINE_PASS" fixed_wheels/*.whl