name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: add rpath to libzip.dylib because there's none
        run: |
          echo "Note: manually added libjvm.dylib to darwin source code."
          install_name_tool -add_rpath @loader_path/. libs/darwin/rt/lib/libzip.dylib
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate wheel for multiple macOS support.
        run: |
          pip install delocate
          delocate-wheel -w fixed_wheels dist/saxonpy-0.0.2-cp*.whl

      # - name: isntall tox
      # delocate-listdeps --all dist/*.whl

      #   run: |
      #     pip install tox

      # - name: run tests with tox
      #   run: |
      #     tox
