name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate libs for multiple macOS support.
        run: |
          pip install delocate
          delocate-wheel -w fixed_wheels -v dist/*.whl
      - name: setup test venv
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install dist/saxonpy-0.0.2-cp38-cp38-macosx_10_14_x86_64.whl
          pip install pytest
          python -m saxonpy
          pytest
      - name: clean up test venv
        run: | 
          deactivate
          rm -Rf .venv


