name: saxonpy jobs
on: [push, workflow_dispatch]
jobs:
  Matrix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15]
        python-version: [3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: build wheel
        run: |
          pip install -r requirements.txt
          python setup.py bdist_wheel
      - name: delocate libs for multiple macOS support.
        run: |
          pip install delocate
      - name: add dynamic lib locations
        run: | 
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libnet.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libosxui.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libawt.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libmlib_image.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libawt_lwawt.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libjsound.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libjawt.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libfontmanager.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libjpeg.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/liblcms.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libAppleScriptEngine.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libunpack.dylib
          install_name_tool -change @loader_path/libjvm.dylib ${JAVA_HOME_8_X64}jre/lib/server/libjvm.dylib  src/saxonc_home/rt/lib/libosx.dylib

          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libnet.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libosxui.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libawt.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libmlib_image.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libawt_lwawt.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libjsound.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libjawt.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libfontmanager.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libjpeg.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/liblcms.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libAppleScriptEngine.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libunpack.dylib
          install_name_tool -add_rpath ${JAVA_HOME_8_X64}jre/lib/server src/saxonc_home/rt/lib/libosx.dylib
      - name: delocate with all listing
        run: |
          delocate-listdeps --all dist/*.whl
      # delocate-wheel -w fixed_wheels -v dist/*.whl
      # - name: isntall tox
      # delocate-listdeps --all dist/*.whl

      #   run: |
      #     pip install tox

      # - name: run tests with tox
      #   run: |
      #     tox
